name = "any"
main = "worker.js"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]
workers_dev = true


# 可选：设置自定义域名（需要先在 Cloudflare 配置）
# routes = [
#   { pattern = "your-domain.com/*", zone_name = "your-domain.com" }
# ]
